# Generated by Django 5.1 on 2024-08-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStocksAlphaVantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=20)),
                ('assetType', models.CharField(max_length=20)),
                ('ipoDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
