# Generated by Django 5.1 on 2024-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tickers_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentaldata',
            name='last_split_factor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
