# Generated by Django 5.1 on 2024-08-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tickers_handler', '0002_alter_fundamentaldata_last_split_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentaldata',
            name='fifty_two_week_high',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fundamentaldata',
            name='fifty_two_week_low',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
